# Generated by Django 4.2.2 on 2023-07-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=30)),
                ('dsnt', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('fare', models.CharField(max_length=30)),
                ('layover', models.CharField(max_length=30)),
            ],
        ),
    ]
