# Generated by Django 4.2.2 on 2023-07-13 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_persflights_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights',
            name='provider',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flights',
            name='time',
            field=models.TimeField(max_length=30),
        ),
    ]
