# Generated by Django 4.2.2 on 2023-08-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_flights_date_flights_provider_alter_flights_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=30)),
                ('cd', models.CharField(max_length=30)),
                ('cl', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
    ]
