# Generated by Django 4.2.2 on 2023-08-03 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_rename_flights_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='provider',
            new_name='provideri',
        ),
        migrations.AddField(
            model_name='flight',
            name='providern',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='cd',
            field=models.CharField(max_length=125),
        ),
    ]
