# Generated by Django 4.2.2 on 2023-08-03 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_provider_flight_provideri_flight_providern_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='fare',
            new_name='bclass',
        ),
        migrations.AddField(
            model_name='flight',
            name='bfare',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='eclass',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='efare',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
