# Generated by Django 4.2.2 on 2023-08-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_fare_flight_bclass_flight_bfare_flight_eclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='bclass',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dsnt',
            new_name='ProviderLogo',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='eclass',
            new_name='ProviderName',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='efare',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='time',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='bfare',
            new_name='bFare',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='provideri',
            new_name='bSeats',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='providern',
            new_name='eFare',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='src',
            new_name='eSeats',
        ),
    ]
