# Generated by Django 4.2.2 on 2023-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_itinerary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
