# Generated by Django 4.2.2 on 2023-08-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_itineraryday_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='OfferPrice',
            field=models.IntegerField(default=168000, max_length=30),
            preserve_default=False,
        ),
    ]
