# Generated by Django 4.2.2 on 2023-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_itinerary_offerprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='OfferPrice',
            field=models.IntegerField(),
        ),
    ]
